version: "3"
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  app:
    # Specify git repo branch and directory for build
    build: https://github.com/andrewspringman/jumpingJack.git#master:app
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      - "traefik.backend=app-be"
      - "traefik.frontend.rule=Host:app.localhost"
  blog:
    # Specify git repo branch and directory for build
    build: https://github.com/andrewspringman/jumpingJack.git#master:blog
    volumes:
      - ./blog:/usr/share/nginx/html
    labels:
      - "traefik.backend=blog-be"
      - "traefik.frontend.rule=Host:blog.localhost"
  website:
    # Specify git repo branch and directory for build
    build: https://github.com/andrewspringman/jumpingJack.git#master:website
    volumes:
      - ./website:/usr/share/nginx/html
    labels:
      - "traefik.backend=website-be"
      - "traefik.frontend.rule=Host:localhost"
